apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cilium
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml

configMapGenerator:
- name: cilium-helm-chart-values
  files:
  - values.yaml

configurations:
  - kustomizeconfig.yaml
